language: node_js
node_js:
  - "8"

script:
  - yarn build

deploy:
  provider: s3
  bucket: content.demo1.labmicrofrontendexample.com
  local_dir: content
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
